class TokenType:
    INTEGER, PLUS, MINUS, MUL, DIV, EOF, RPAREN, LPAREN, LESS, GREATHER, EQUAL, NOT_EQUAL, \
        LESS_EQ, GREATHER_EQ, STRING, ASSIGN = (
            'INTEGER', 'PLUS', 'MINUS', 'MUL', 'DIV', 'EOF', 'RPAREN', 'LPAREN', 'LESS', 'GREATHER',
            'EQUAL', 'NOT_EQUAL', 'LESS_EQ', 'GREATHER_EQ', 'STRING', 'ASSIGN'
        )